apiVersion: v1
kind: Service
metadata:
  name: hello-minikube
spec:
  type: LoadBalancer
#  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 30000